version: '3'

services:
  web:
    command: wait-for-it.sh postgres:5432 -- sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./project/:/usr/src/app

  celery_beat:
    volumes:
      - ./project/:/usr/src/app

  celery_worker:
    volumes:
      - ./project/:/usr/src/app